version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - echo "==> CODEBUILD_GIT_BRANCH = $CODEBUILD_GIT_BRANCH "
      - echo "Creating .env file"
      - echo "BRANCH_NAME=$BRANCH_NAME\nMONGO_USERNAME=$MONGO_USERNAME\nMONGO_PASSWORD=$MONGO_PASSWORD" > .env
  build:
    commands:
      - echo Starting Deployment
      - serverless deploy --SERVICE_NAME $SERVICE_NAME --MONGO_USERNAME $MONGO_USERNAME --MONGO_PASSWORD $MONGO_PASSWORD
  post_build:
    commands:
      - echo Build Completed on `date`
